Refactor install to run completely every time
This way everything is up to date.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -44,24 +44,25 @@ ensure_link "$dotdir/vimrc" "$HOME/.vimrc"
 }
 
 install_vim() {
-
 (
 bundledir=$HOME/.vim/bundle
 
 ensure_clone() {
 # Wow, this is gross!
 # Wow, this is cool.
-cd "$bundledir" || exit
-git clone "$1" || cd "$2" || git pull "$1"
+#cd "$bundledir" || exit
+git clone "$1" || ( cd "$2" && git pull "$1" )
+# if clone fails
+# subshell cd, etc
 }
 
 
-cd "$bundledir" || exit
+cd "$HOME/.vim" || exit
 ensure_clone 'https://github.com/tpope/vim-pathogen' 'vim-pathogen'
-ensure_link "$HOME/.vim/bundle/vim-pathogen/autoload/pathogen.vim" \
+ensure_link "$HOME/.vim/vim-pathogen/autoload/pathogen.vim" \
 	"$HOME/.vim/autoload/pathogen.vim"
 
-
+cd "$bundledir" || exit
 ensure_clone "https://github.com/vim-syntastic/syntastic" "syntastic"
 ensure_clone "https://github.com/tpope/vim-fugitive" "vim-fugitive"
 ensure_clone "https://github.com/tpope/vim-sleuth" "vim-sleuth"
@@ -117,48 +118,17 @@ install_fluxbox()
 {
 (
 dotdir="$HOME/dotfiles"
-#echo "$dotdir/fluxbox/init"
 ensure_link "$dotdir/fluxbox/init" "$HOME/.fluxbox/init"
 ensure_link "$dotdir/fluxbox/keys" "$HOME/.fluxbox/keys"
 ensure_link "$dotdir/fluxbox/menu" "$HOME/.fluxbox/menu"
-python "$dotdir/fluxbox/theme.py" > "$HOME/.fluxbox/styles/theme0"
+python "$dotdir/fluxbox/themer" '906090' > "$dotdir/fluxbox/styles/theme"
 )
 }
 
 main() {
-  case "$@" in
-    vim)
-      install_vim
-      exit
-      ;;
-    dotfiles)
-      install_dotfiles
-      exit
-      ;;
-    debs)
-      install_debs
-      exit
-      ;;
-    fluxbox)
-      install_fluxbox
-      exit
-      ;;
-    all)
-      #install_debs
-      install_dotfiles
-      install_vim
-      install_fluxbox
-      exit
-      ;;
-    *)
-      echo "Wrong arguments: $*"
-      echo "Usage: install dotfiles"
-      echo "Usage: install vim"
-      echo "Usage: install debs"
-      echo "Usage: install all"
-      exit
-      ;;
-  esac
+install_dotfiles
+install_vim
+install_fluxbox
 }
 
-main "$@"
+main
